language: ruby
rvm:
  - 2.6

script:
  - bundle exec jekyll build

before_deploy:
  - pushd _site
  - rm CNAME
  - touch .nojekyll
  - popd

deploy:
  # Publish the staging branch to solid.github.io
  - provider: pages
    on:
      branch: staging
    local_dir: _site
    repo: solid/solid.github.io
    target_branch: master
    skip_cleanup: true
    keep_history: true
    allow_empty_commit: true
    github_token: $GITHUB_TOKEN
