language: ruby
rvm:
  - 2.6

before_install:
  - nvm install stable

script:
  - bundle exec jekyll build
  - bundle exec htmlproofer
      --assume_extension --root-folder _site
      --allow_hash_href
      --typhoeus_config '{"timeout":60}'
      --http-status-ignore '0,301,302,403,410,429,500,501,502,503,999'
      _site
  - npx yaspeller-ci --dictionary dictionary.json **/*.md _site

before_deploy:
  - pushd _site
  - rm CNAME
  - touch .nojekyll
  - popd

deploy:
  # Publish the staging branch to solid.github.io
  - provider: pages
    on:
      branch: staging
    local_dir: _site
    repo: solid/solid.github.io
    target_branch: master
    skip_cleanup: true
    keep_history: true
    allow_empty_commit: true
    github_token: $GITHUB_TOKEN
